namespace: staging

backend:
  image: abhayshaw0125/takehome-backend-staging:latest
  replicas: 2
  port: 8000
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "200m"
      memory: "256Mi"

frontend:
  image: abhayshaw0125/takehome-frontend-staging:latest
  replicas: 2
  port: 80
  resources:
    requests:
      cpu: "50m"
      memory: "64Mi"
    limits:
      cpu: "100m"
      memory: "128Mi"

ingress:
  host: staging.ewma.local
  className: nginx

environment: staging
