namespace: production

backend:
  image: abhayshaw0125/takehome-backend-prod:stable
  replicas: 5
  port: 8000
  resources:
    requests:
      cpu: "200m"
      memory: "256Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"

frontend:
  image: abhayshaw0125/takehome-frontend-prod:stable
  replicas: 3
  port: 80
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "200m"
      memory: "256Mi"

ingress:
  host: prod.ewma.local
  className: nginx

environment: production
hpa:
  enabled: true   
  backend:
    minReplicas: 2
    maxReplicas: 5
    targetCPU: 70
    targetMemory: 80
  frontend:
    minReplicas: 2
    maxReplicas: 4
    targetCPU: 75
    targetMemory: 85