name: CD / Deploy with Helm

on:
  workflow_dispatch:   # manual trigger
  push:
    branches: [ "main" ]   # run on push to main

jobs:
  deploy-staging:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: v1.27.0

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.13.0

      # Spin up a temporary Kind cluster inside the GitHub runner
      - name: Create Kind cluster
        uses: helm/kind-action@v1
        with:
          cluster_name: ewma-ci
          wait: 60s

      - name: Deploy Helm chart to Staging
        run: |
          helm upgrade --install ewma-staging ./k8s \
            --namespace staging \
            --values ./k8s/values.yaml \
            --wait

      - name: Verify deployment
        run: kubectl get all -n staging

  deploy-production:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: deploy-staging
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: v1.27.0

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.13.0

      - name: Deploy Helm chart to Production
        run: |
          helm upgrade --install ewma-production ./k8s \
            --namespace production \
            --values ./k8s/values-production.yaml \
            --wait

      - name: Verify deployment
        run: kubectl get all -n production
